DROP TABLE IF EXISTS mpa_ratings CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friendships CASCADE;
DROP TABLE IF EXISTS film_likes CASCADE;

CREATE TABLE IF NOT EXISTS mpa_ratings (
                                        mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(100) NOT NULL,
                                     description VARCHAR(500),
                                     release_date DATE,
                                     duration INTEGER CHECK (duration > 0),
                                     mpa_id INTEGER REFERENCES mpa_ratings (mpa_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS genres (
                                     genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genres (
                                          film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
                                          genre_id INTEGER NOT NULL REFERENCES genres (genre_id) ON DELETE RESTRICT,
                                          PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(100) NOT NULL UNIQUE,
                                     login VARCHAR(50) NOT NULL UNIQUE,
                                     name VARCHAR(100) NOT NULL,
                                     birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
                                       user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                                       friend_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                                       is_friend BOOLEAN NOT NULL,
                                       PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
                                     film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
                                     user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                                     PRIMARY KEY (film_id, user_id)
);